#!/usr/bin/env node
/**
 * sandbox-test.js — called by GitHub Actions to run runtime sandbox checks
 * on a comma-separated list of changed skills.
 */

const fs = require('fs');
const path = require('path');
const { sandboxTestSkill } = require('../src/cli.js');

const LOCAL_SKILLS_DIR = path.join(__dirname, '..', 'skills');
const REPORT_PATH = path.join(process.cwd(), 'security-report.md');

const skillsArg = process.argv[2] || '';
const skills = skillsArg.split(',').map(s => s.trim()).filter(Boolean);

if (skills.length === 0) {
  console.log('No skills to sandbox test.');
  process.exit(0);
}

let overallPassed = true;
let report = '';

for (const skill of skills) {
  const srcDir = path.join(LOCAL_SKILLS_DIR, skill);
  if (!fs.existsSync(srcDir)) {
    report += `### \`${skill}\` — ⚠️ SANDBOX SKIPPED\nDirectory not found.\n\n`;
    continue;
  }

  console.log(`\nSandbox testing skill: ${skill}`);
  const result = sandboxTestSkill(srcDir);

  if (result.passed) {
    console.log('  ✅ PASSED');
    report += `### \`${skill}\` — ✅ SANDBOX PASSED\nNo sandbox violations detected.\n\n`;
  } else {
    console.error('  ❌ FAILED');
    overallPassed = false;
    report += `### \`${skill}\` — ❌ SANDBOX FAILED\n`;
    for (const violation of result.violations || []) {
      console.error(`    • ${violation}`);
      report += `- ${violation}\n`;
    }
    report += '\n';
  }
}

if (report) {
  // Append to existing report generated by ci-scan.js when present.
  fs.appendFileSync(REPORT_PATH, `\n\n## Runtime Sandbox Results\n\n${report}`);
}

process.exit(overallPassed ? 0 : 1);
